Library/Models/FeedbackViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Library.Models
{
    public class FeedbackViewModel
    {
        [Required (ErrorMessage= "Please enter your name")]
        [StringLength(10, MinimumLength= 3)]
        public string AuthorName { get; set; }
        
        [Required (ErrorMessage= "Please enter the text of your feedback")]
        [Remote("ValidateInputLength", "Guest")]
        public string Body { get; set; }
        
        public DateTime CreatedAt { get; } = DateTime.Now;
        
        public FeedbackViewModel()
        {
            
        }
        
        public FeedbackViewModel(string authorName, string body, DateTime createdAt)
        {
            AuthorName = authorName;
            Body = body;
            CreatedAt = createdAt;
        }
    }
}

Library/Controllers/GuestController.cs
using System.Web.Mvc;
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Library.Models;

namespace Library.Controllers
{
    /// <summary>
    /// <c>GuestController</c> is a class.
    /// Contains a methods to give ability to left and view feedbacks.
    /// </summary>
    /// <remarks>
    /// This class is useful to interact with guest.
    /// </remarks>
    public class GuestController : Controller
    {
        private readonly IFeedbackService _feedbackService;
        private readonly IMapper _mapper;
        
        public GuestController(IFeedbackService serv)
        {
            _feedbackService = serv;
            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<FeedbackViewModel, FeedbackDto>().ReverseMap();
            }).CreateMapper();
        }

        /// <summary>
        /// This method returns page with all feedbacks.
        /// </summary>
        /// <response code="200">Returns all feedbacks.</response>
        /// <response code="302">Redirects to feedback form.</response>
        public ActionResult Index()
        {
            ViewBag.Feedbacks = _feedbackService.GetFeedbacks();
            return View();
        }
        
        /// <summary>
        /// This method returns page with form to leave your feedbacks.
        /// </summary>
        /// <response code="200">Returns feedback form.</response>
        [HttpGet]
        public ActionResult PostComment()
        {
            return View();
        }

        /// <summary>
        /// This method returns page with form to correct your feedbacks or redirects to main page.
        /// </summary>
        /// <response code="200">Returns feedback form to correct.</response>
        /// <response code="302">Redirects to guest main page.</response>
        [HttpPost]
        public ActionResult PostComment(FeedbackViewModel feedbackViewModel)
        {
            if (ModelState.IsValid)
            {
               var feedbackDto = _mapper.Map<FeedbackDto>(feedbackViewModel);
                _feedbackService.CreateFeedback(feedbackDto);
                
                return RedirectToAction("Index");
            }

            return View(feedbackViewModel);
        }
        
        /// <summary>
        /// This method checks if the length of feedback body between 50 and 500 symbols.
        /// </summary>
        /// <response code="200">Returns validation message.</response>
        [HttpGet]
        public JsonResult ValidateInputLength(string body)
        {
            return body.Length < 50 || body.Length > 500 ? 
                Json("Incorrect length of your feedback, it is too short(((",JsonRequestBehavior.AllowGet) :
                Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Library/Controllers/HomeController.cs
using System.Web.Mvc;
using BLL.Interfaces;

namespace Library.Controllers
{
    /// <summary>
    /// <c>HomeController</c> is a class.
    /// Contains a method that returns main page.
    /// </summary>
    /// <remarks>
    /// This class can show a page with articles previews.
    /// </remarks>
    public class HomeController : Controller
    {
        private readonly IArticleService _articleService;
        
        public HomeController(IArticleService serv)
        {
            _articleService = serv;
        }
        
        /// <summary>
        /// This method returns main page.
        /// </summary>
        /// <response code="200">Returns all articles previews.</response>
        public ActionResult Index()
        {
            return View(_articleService.GetArticles());
        }
    }
}

Library/Controllers/QuestionnaireController.cs
using System.Web.Mvc;
using BLL.Interfaces;
using Library.Helpers;

namespace Library.Controllers
{
    /// <summary>
    /// <c>GuestController</c> is a class.
    /// Contains a methods to pass questionnaire and to look its statistics.
    /// </summary>
    /// <remarks>
    /// This class can is useful to pass questionnaire.
    /// </remarks>
    public class QuestionnaireController : Controller
    {
        private readonly IQuestionService _questionService;
        private readonly IAnswerService _answerService;
        
        public QuestionnaireController(IQuestionService questionService, IAnswerService answerService)
        {
            _questionService = questionService;
            _answerService = answerService;
        }
        
        /// <summary>
        /// This method returns another action of controller.
        /// </summary>
        /// <response code="200">Returns view depending on result of another action.</response>
        public ActionResult Index()
        {
            return View(_questionService.GetQuestions());
        }

        /// <summary>
        /// This method returns page with questionnaire form.
        /// </summary>
        /// <response code="200">Returns questionnaire form to correct.</response>
        /// <response code="302">Redirects to questionnaire statistics page.</response>
        [HttpGet]
        public ActionResult QuestionnaireResult()
        {
            var queryParamsList = Request.AnswersId();

            foreach (var id in queryParamsList)
                _answerService.Checked(id);

            return QuestionnaireResult(Request.QueryString["Name"]);
        }
        
        /// <summary>
        /// This method returns page with questionnaire statistics.
        /// </summary>
        /// <response code="200">Returns questionnaire statistics.</response>
        [HttpPost]
        public ActionResult QuestionnaireResult(string name)
        {
            ViewBag.Name = name;

            return View(_questionService.GetQuestions());
        }
    }
}

Library/Views/Guest/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-8">
    <div>
        @foreach (var feedback in ViewBag.Feedbacks)
        {
            <p>@feedback.Body</p>
            <p>@feedback.AuthorName - @feedback.CreatedAt</p>
            <hr>
        }
    </div>
    <div class="p-1 m-5">
        <a href="/Guest/PostComment">
            <button type="button" class="btn btn-primary btn-lg btn-block" >Click here to left your comment</button>
        </a>
    </div>
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Guest/PostComment.cshtml
@model Library.Models.FeedbackViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-8">
       <h5 class="mb-2">For your opinion:</h5>
           @using (Html.BeginForm("PostComment", "Guest", FormMethod.Post))
           {
               <div class="form-group">
                   <label for="Name">Author`s name:</label>
                   @Html.EditorFor(model => model.AuthorName, new {htmlAttributes = new {@class = "form-control"}})
                   @Html.ValidationMessageFor(m => m.AuthorName)
               </div>
               <div class="form-group">
                   <label for="Feedback">Feedback:</label><br>
                    @Html.TextAreaFor(model => model.Body, new {@class = "form-control", rows = 10, col = 45})
                   @Html.ValidationMessageFor(model => model.Body)
               </div>
               <div class="form-group">
                   <input type="submit" value="Send" class="form-control bg-dark text-white">
               </div>
           }
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Home/Index.cshtml
@model IEnumerable<BLL.DTO.ArticleDto>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-8">
    <ul>
        @foreach (var article in Model)
        {
            <h2>@article.Heading</h2>
            <h5>@article.Description</h5>
            <div class="fakeimg">Fake Image</div>
            <p>@article.Body</p>
        }
    </ul>
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link active" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>
   

Library/Views/Questionnaire/Index.cshtml
@using BLL.DTO

@model IEnumerable<BLL.DTO.QuestionDto>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-8">
    @using (Html.BeginForm("QuestionnaireResult", "Questionnaire", FormMethod.Get))
    {
        <div class="form-group">
            <h5 class="m-0 pb-2">Your name:</h5>
            <input type="text" required size="30" maxlength="30" name="Name" id="Name" class="form-control"/>
        </div>
        <div class="form-group">
            @foreach (var question in Model)
            {
                <h5 class="m-0 pb-2">@question.Text</h5>

                <div class="form-check pl-4">
                    @if (question.QuestionType == QuestionTypesDto.Radio)
                    {
                        foreach (var answer in question.Answers)
                        {
                            <input required class="form-check-input" type="radio" name="@question.Id" id="@answer.Text" value="@answer.Id">
                            <label class="form-check-label" for="@answer.Text">@answer.Text</label>
                            <br>
                        }
                    }
                    else
                    {
                        foreach (var answer in question.Answers)
                        {
                            <input class="form-check-input" type="checkbox" name="@question.Id" id="@answer.Text" value="@answer.Id">
                            <label class="form-check-label" for="@answer.Text">@answer.Text</label>
                            <br>
                        }
                    }
                </div>
            }
        </div>
        <div class="form-group mt-3">
            <input type="submit" value="Send" class="form-control bg-dark text-white">
        </div>
    }
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Questionnaire/QuestionnaireResult.cshtml
@using BLL.DTO
@model IEnumerable<BLL.DTO.QuestionDto>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-8">
    <h5 class="m-0 pb-2">Thanks for your answer, @ViewBag.Name </h5>
    
    @foreach (var question in Model)
    {
        if (question.QuestionType == QuestionTypesDto.Radio)
        {
            <h5 class="m-0 mt-3 pb-2">@question.Text</h5>
            @Html.UnorderedList(question.Answers)
        }
        else
        {
            <h5 class="m-0 mt-3 pb-2">@question.Text</h5>
            @InlineHelpers.OrderedList(question.Answers)
        }
    }
</div>
<div class="col-sm-4">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link" href="/Home/Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Guest/Index">Guest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Questionnaire/Index">Questionnaire</a>
        </li>
    </ul>
    <hr class="d-sm-none">
</div>

Library/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <title>Document</title>
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
        .input-validation-error{
            border: 2px solid #f00;
            background-color: #fee;
        }
        </style>
</head>
<body>
<nav class="navbar navbar-light bg-secondary">
    <a class="navbar-brand text-white" href="/Home/Index" id="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
            <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
        </svg>
        Library
    </a>
</nav>

<div class="container" style="margin-top:30px; max-width: 80%;">
    <div class="row">
        @RenderBody()
        
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @RenderSection("Scripts", required: false)
    </div>
</div>

<footer class="footer bg-secondary text-center pb-2">
    <p class="text-white p-2 m-0">&copy;Volodymyr Shenheliia, vladimir231200@gmail.com</p>
    <a class="text-red pb-2 m-0" href="#"><u>Link to start of the page</u></a>
</footer>
</body>
</html>